services:
  redis:
    image: redis
    ports:
      - 6379:6379
  samsion:
    image: samsion
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - redis